name: RAG
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cryptography=45.0.7
  - ld_impl_linux-64=2.44
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libuuid=2.41.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.2
  - pip=25.2
  - pypdfium2=4.30.1
  - python=3.11.13
  - python_abi=3.11
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - brotli==1.1.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - docx==0.2.4
      - faiss-cpu==1.12.0
      - fastapi==0.116.1
      - ffmpy==0.6.1
      - filelock==3.19.1
      - fsspec==2025.9.0
      - gradio==5.45.0
      - gradio-client==1.13.0
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.1.9
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - jinja2==3.1.6
      - lxml==6.0.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - numpy==2.3.3
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.2
      - pillow==11.3.0
      - pycparser==2.23
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pymupdf==1.26.4
      - pypdf==6.0.0
      - pytesseract==0.3.13
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - rank-bm25==0.2.2
      - requests==2.32.5
      - rich==14.1.0
      - ruff==0.13.0
      - safehttpx==0.1.6
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.47.3
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - typer==0.17.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - websockets==15.0.1
